# Generated by Django 3.2.2 on 2021-05-11 16:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pwd',
            field=models.CharField(default=123, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='rpwd',
            field=models.CharField(default=123, max_length=100),
        ),
    ]
