# Generated by Django 3.2.2 on 2021-05-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210511_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='signup',
        ),
    ]
