# Generated by Django 3.2.2 on 2021-05-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_rename_students_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signup_table',
        ),
    ]
