# Generated by Django 3.2.2 on 2021-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_signup_table_yearofjoining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_table',
            name='pwd',
        ),
        migrations.AlterField(
            model_name='signup_table',
            name='yearofjoining',
            field=models.IntegerField(),
        ),
    ]
